before_install:
- npm install n
- sudo ./node_modules/.bin/n stable
- rm -rf ~/.nvm

# whitelist
branches:
  only:
    - gh-pages

language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - sudo nvm install -g grunt

script: grunt test --verbose --force
