before_install:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
- npm install -g npm@latest

# whitelist
branches:
  only:
    - gh-pages

language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - cd tests
  - npm install -g grunt-cli
  - npm install -g grunt
  - grunt --version

script: grunt test --verbose --force
